### ISSUE TITLE
Sentry seems to have broken my app..

### ISSUE THREAD

**Issue by getFrontend** [adrianhajdin/iphone#5]
I did everything correctly until I restarted the server and the error started to appear:

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
```

![Снимок1942338_vite-error](https://github.com/adrianhajdin/iphone/assets/118477025/11415a06-256f-46e3-8ed4-3838e3a77050)

**Comment by Shafi-Anwar** [comment]
install it by npm i -g @sentry/react

**Comment by getFrontend** [comment]
Unfortunately the global installation of Sentry dependencies did not help. Searching for a solution on the Internet showed that it may be related specifically to bugs in the Vite builder itself.

A specific working solution for me was: temporarily commenting out `sentryVitePlugin` in `vite.config.js`

```
plugins: [
    react(),
    // sentryVitePlugin({
    //   org: "seoromeo",
    //   project: "javascript-react",
    // }),
  ]
```

After that the server restarted successfully, I uncommented the strings and everything worked on localhost.

No problems were encountered when deploing on Vercel, which is pleasing 😎
